export const INTENTS = Object.freeze({
  ASK_COUNTRY: "ASK_COUNTRY",
  ASK_PHONE: "ASK_PHONE",
  INVALID_PHONE: "INVALID_PHONE",
  CONFIRM_OPERATOR: "CONFIRM_OPERATOR",
  ASK_SERVICE_TYPE: "ASK_SERVICE_TYPE",
  ASK_PRODUCT: "ASK_PRODUCT",
  ORDER_SUMMARY: "ORDER_SUMMARY",
  PAYMENT_LINK: "PAYMENT_LINK",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  TOPUP_SUCCESS: "TOPUP_SUCCESS",
  FALLBACK_RESET: "FALLBACK_RESET"
});
