export const STATES = Object.freeze({
  WAITING_COUNTRY: "WAITING_COUNTRY",
  WAITING_PHONE: "WAITING_PHONE",
  WAITING_OPERATOR_CONFIRM: "WAITING_OPERATOR_CONFIRM",
  WAITING_SERVICE_TYPE: "WAITING_SERVICE_TYPE",
  WAITING_AMOUNT: "WAITING_AMOUNT",
  WAITING_ORDER_CONFIRM: "WAITING_ORDER_CONFIRM",
  WAITING_PAYMENT: "WAITING_PAYMENT",
  PROCESSING_TOPUP: "PROCESSING_TOPUP",
  DONE: "DONE",
  FAILED: "FAILED"
});
